# Table S2: reproduction of published values
#
# Reads inst/reproduce/output/reproduce_results.csv (generated by
# inst/reproduce/reproduce_published.R). Writes
# inst/paper/output/tables/tableS2_reproduction.tex and
# inst/paper/output/numbers/tableS2_reproduction.csv.

source(file.path("inst", "paper", "figures_and_tables", "settings.R"))
src <- file.path("inst", "reproduce", "output", "reproduce_results.csv")
rr <- utils::read.csv(src, stringsAsFactors = FALSE)
esc <- function(x) gsub("_", "\\\\_", gsub("&", "\\\\&", gsub("%", "\\\\%", x)))
note_id <- cumsum(rr$judgment %in% c("EXPLAINED", "INFO"))
mark <- ifelse(rr$judgment %in% c("EXPLAINED", "INFO"), paste0("\\tnote{", letters[note_id], "}"), "")
body <- paste0(esc(rr$source), " & ", esc(rr$quantity), " & ",
               formatC(rr$published, format = "g", digits = 6), " & ",
               ifelse(is.na(rr$computed), "--", formatC(rr$computed, format = "f", digits = 4)), " & ",
               rr$judgment, mark, " \\\\")
tab <- table(factor(rr$judgment, levels = c("PASS", "EXPLAINED", "FAIL", "INFO")))
notes <- c(paste0("PASS: ", tab[["PASS"]], ", EXPLAINED: ", tab[["EXPLAINED"]], ", FAIL: ",
                  tab[["FAIL"]], ", INFO: ", tab[["INFO"]], ". Tolerances are given in ",
                  "\\texttt{inst/reproduce/output/reproduce\\_summary.md} of the package."),
           if (any(rr$judgment %in% c("EXPLAINED", "INFO"))) {
             paste0("[", letters[seq_len(sum(rr$judgment %in% c("EXPLAINED", "INFO")))], "] ",
                    esc(rr$reason[rr$judgment %in% c("EXPLAINED", "INFO")]))
           })
write_table_tex("tableS2_reproduction",
                caption = "Reproduction of published values with the CorOncoEndpoints package.",
                label = "tab:reproduction", align = "p{3.2cm}p{6.4cm}rrl",
                header = "Source & Quantity & Published & Computed & Judgment \\\\",
                body = body, notes = notes, size = "\\scriptsize")
write_numbers("tableS2_reproduction",
              key = c(paste0("computed_row", seq_len(nrow(rr))), paste0("n_", names(tab))),
              value = c(rr$computed, as.vector(tab)),
              description = c(paste(rr$source, rr$quantity, sep = ": "),
                              paste("number of", names(tab))),
              source = src)
