# Table S3 (parts a to c): validation of the generator against the
# theoretical quantities
#
# Reads inst/validation/output/validate_generator.csv (generated by
# inst/validation/validate_generator.R). Writes
# inst/paper/output/tables/tableS3a_generator_validation.tex (and b, c) and
# inst/paper/output/numbers/tableS3_generator_validation.csv.

source(file.path("inst", "paper", "figures_and_tables", "settings.R"))
src <- file.path("inst", "validation", "output", "validate_generator.csv")
vg <- utils::read.csv(src, stringsAsFactors = FALSE)
scen <- unique(vg$scenario)
parts <- split(scen, ceiling(seq_along(scen) / 2))
esc <- function(x) gsub("_", "\\\\_", gsub("<=", "$\\\\le$", x))
for (i in seq_along(parts)) {
  v <- vg[vg$scenario %in% parts[[i]], ]
  body <- c()
  for (s in parts[[i]]) {
    w <- v[v$scenario == s, ]
    body <- c(body, if (length(body) > 0) "\\midrule",
              paste0(ifelse(seq_len(nrow(w)) == 1, paste0("\\texttt{", esc(s), "}"), ""), " & ",
                     esc(w$quantity), " & ", fmt_num(w$theory, 5), " & ", fmt_num(w$estimate, 5),
                     " & ", fmt_num(w$se, 5), " & ", fmt_num(w$z, 2), " & ", w$judgment, " \\\\"))
  }
  write_table_tex(paste0("tableS3", letters[i], "_generator_validation"),
                  caption = paste0("Validation of the generator (part ", letters[i], " of ",
                                   length(parts), "): theoretical values and Monte Carlo ",
                                   "estimates for the scenarios ",
                                   paste0("\\texttt{", esc(parts[[i]]), "}", collapse = " and "), "."),
                  label = paste0("tab:generator", letters[i]), align = "p{2.4cm}p{4.2cm}rrrrl",
                  header = "Scenario & Quantity & Theory & Estimate & SE & $z$ & Judgment \\\\",
                  body = body,
                  notes = paste0("Estimates are means over 40 batches of 50,000 patients; SE is ",
                                 "the standard deviation over batches divided by $\\sqrt{40}$ and ",
                                 "$z = (\\mathrm{estimate} - \\mathrm{theory}) / \\mathrm{SE}$. ",
                                 "PASS when $|z| < 4$. The scenarios are defined in ",
                                 "\\texttt{inst/validation/validate\\_generator.R} of the package."),
                  size = "\\scriptsize\\setlength{\\tabcolsep}{3pt}")
}
tab <- table(factor(vg$judgment, levels = c("PASS", "FAIL")))
write_numbers("tableS3_generator_validation",
              key = c("n_pass", "n_fail", "n_rows", "max_abs_z"),
              value = c(tab[["PASS"]], tab[["FAIL"]], nrow(vg), max(abs(vg$z), na.rm = TRUE)),
              description = c("number of PASS", "number of FAIL", "number of comparisons",
                              "largest |z|"),
              source = src)
