# Validation of RequiredEvents(): simulated power of the log-rank test
#
# Run from the package root, after devtools::load_all() or
# library(CorOncoEndpoints):
#   source("inst/validation/validate_design.R")
# Requires the survival package. Writes inst/validation/output/validate_design.csv
# and inst/validation/output/validate_design.md (generated, do not edit by hand).
#
# Trials with 350 patients per group and uniform accrual over 24 months are
# analysed when the number of events given by RequiredEvents() (one-sided
# alpha 0.025, power 0.8) is reached. PASS when the simulated power is within
# 4 Monte Carlo standard errors of 0.8. The OS design based on the hazard ratio
# implied by the medians (exponential assumption) is reported as INFO.

if (!exists("OncoArm")) library(CorOncoEndpoints)
if (!requireNamespace("survival", quietly = TRUE)) {
  stop("The survival package is required for this script.")
}
out_dir <- file.path("inst", "validation", "output")
dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)

ctl <- OncoArm(pfs.median = 6, orr = 0.30, resp.cor = 0.40, death.prop = 0.15,
               os.median = 15, pps.hr.resp = 0.6)
trt <- OncoArm(pfs.median = 6 / 0.7, orr = 0.45, resp.cor = 0.40, death.prop = 0.15,
               pps.hazard = ctl$gam0, pps.hr.resp = 0.6)
arms <- list(Control = ctl, Treatment = trt)
n <- c(350, 350)
nrep <- 4000

power_at <- function(events, endpoint) {
  d <- rOncoEndpoints(nsim = nrep, n = n, arms = arms, a.time = c(0, 24), seed = 99)
  cut <- CutoffData(d, EventTime(d, events, endpoint))
  tte <- cut[[paste0(endpoint, "_tte")]]
  ev <- cut[[paste0(endpoint, "_event")]]
  z <- vapply(split(seq_len(nrow(cut)), cut$sim), function(i) {
    sd <- survival::survdiff(survival::Surv(tte[i], ev[i]) ~ cut$group[i])
    o_e <- sd$obs[2] - sd$exp[2]
    o_e / sqrt(sd$var[2, 2])
  }, numeric(1))
  mean(z < -stats::qnorm(0.975))
}

rows <- list()
mcse <- sqrt(0.8 * 0.2 / nrep)
for (ep in c("os", "pfs")) {
  r <- RequiredEvents(arms, n = n, a.time = c(0, 24), endpoint = ep)
  pw <- power_at(r$events, ep)
  rows[[length(rows) + 1L]] <- data.frame(
    endpoint = ep, method = "RequiredEvents (average hazard ratio)",
    hazard_ratio = r$ahr, events = r$events, power = pw, mcse = mcse,
    judgment = if (abs(pw - 0.8) < 4 * mcse) "PASS" else "FAIL",
    stringsAsFactors = FALSE)
}
hr_med <- QuantileEndpoint(ctl, endpoint = "os") / QuantileEndpoint(trt, endpoint = "os")
d_med <- ceiling((stats::qnorm(0.975) + stats::qnorm(0.8))^2 / (0.25 * log(hr_med)^2))
rows[[length(rows) + 1L]] <- data.frame(
  endpoint = "os", method = "Schoenfeld with the hazard ratio of the medians",
  hazard_ratio = hr_med, events = d_med, power = power_at(d_med, "os"), mcse = mcse,
  judgment = "INFO", stringsAsFactors = FALSE)

res <- do.call(rbind, rows)
utils::write.csv(res, file.path(out_dir, "validate_design.csv"), row.names = FALSE)
md <- c("# Validation of RequiredEvents()",
        "",
        "Generated by `inst/validation/validate_design.R`. Do not edit by hand.",
        "",
        paste0(nrep, " simulated trials, 350 patients per group, uniform accrual over 24 ",
               "months, one-sided alpha 0.025, target power 0.8."),
        "",
        "| Endpoint | Method | Hazard ratio | Events | Simulated power | MCSE | Judgment |",
        "|---|---|---|---|---|---|---|",
        sprintf("| %s | %s | %.4f | %d | %.4f | %.4f | %s |", res$endpoint, res$method,
                res$hazard_ratio, as.integer(res$events), res$power, res$mcse, res$judgment),
        "")
writeLines(md, file.path(out_dir, "validate_design.md"))
print(res)
