// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// generate_arm_cpp
List generate_arm_cpp(int nsim, int n, double lam_p, double theta, double c_resp, double z_tau, double tau, int os_model, double pi_death, double gam0, double gam1, double lam_o, double c_dec, NumericVector grid_g, double grid_h, int ttr_mode, double ttr_rate, NumericVector a_time, NumericVector a_cum, double d_hazard);
RcppExport SEXP _CorOncoEndpoints_generate_arm_cpp(SEXP nsimSEXP, SEXP nSEXP, SEXP lam_pSEXP, SEXP thetaSEXP, SEXP c_respSEXP, SEXP z_tauSEXP, SEXP tauSEXP, SEXP os_modelSEXP, SEXP pi_deathSEXP, SEXP gam0SEXP, SEXP gam1SEXP, SEXP lam_oSEXP, SEXP c_decSEXP, SEXP grid_gSEXP, SEXP grid_hSEXP, SEXP ttr_modeSEXP, SEXP ttr_rateSEXP, SEXP a_timeSEXP, SEXP a_cumSEXP, SEXP d_hazardSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nsim(nsimSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type lam_p(lam_pSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type c_resp(c_respSEXP);
    Rcpp::traits::input_parameter< double >::type z_tau(z_tauSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type os_model(os_modelSEXP);
    Rcpp::traits::input_parameter< double >::type pi_death(pi_deathSEXP);
    Rcpp::traits::input_parameter< double >::type gam0(gam0SEXP);
    Rcpp::traits::input_parameter< double >::type gam1(gam1SEXP);
    Rcpp::traits::input_parameter< double >::type lam_o(lam_oSEXP);
    Rcpp::traits::input_parameter< double >::type c_dec(c_decSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type grid_g(grid_gSEXP);
    Rcpp::traits::input_parameter< double >::type grid_h(grid_hSEXP);
    Rcpp::traits::input_parameter< int >::type ttr_mode(ttr_modeSEXP);
    Rcpp::traits::input_parameter< double >::type ttr_rate(ttr_rateSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a_time(a_timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a_cum(a_cumSEXP);
    Rcpp::traits::input_parameter< double >::type d_hazard(d_hazardSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_arm_cpp(nsim, n, lam_p, theta, c_resp, z_tau, tau, os_model, pi_death, gam0, gam1, lam_o, c_dec, grid_g, grid_h, ttr_mode, ttr_rate, a_time, a_cum, d_hazard));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CorOncoEndpoints_generate_arm_cpp", (DL_FUNC) &_CorOncoEndpoints_generate_arm_cpp, 20},
    {NULL, NULL, 0}
};

RcppExport void R_init_CorOncoEndpoints(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
