#' Data observed at an analysis cutoff
#'
#' @description
#' Restricts data generated by \code{\link{rOncoEndpoints}} to patients
#' enrolled before an analysis cutoff (calendar time) and censors PFS and OS at
#' the cutoff. Response is counted as observed when the patient responded and,
#' if a time to response was generated, the response occurred before the
#' cutoff and before dropout.
#'
#' @param data A data frame returned by \code{\link{rOncoEndpoints}}.
#' @param cutoff Calendar time of the cutoff: a scalar, or one value per
#'   simulated trial in \code{data}, in increasing order of \code{sim} (as
#'   returned by \code{\link{EventTime}}). \code{NA} means no cutoff.
#' @return The rows of \code{data} with \code{accrual_time < cutoff}, with
#'   \code{pfs_tte}, \code{pfs_event}, \code{os_tte}, \code{os_event},
#'   \code{pfs_calendar_time} and \code{os_calendar_time} recomputed, and the
#'   added columns \code{response_obs} and \code{cutoff}.
#' @examples
#' arm <- OncoArm(pfs.median = 6, orr = 0.3, resp.cor = 0.4, death.prop = 0.15,
#'                os.median = 15, resp.timing = "ttr", resp.tau = 1.5,
#'                ttr.median = 2.5)
#' dat <- rOncoEndpoints(nsim = 2, n = 100, arms = arm, a.time = c(0, 12),
#'                       seed = 1)
#' cut <- CutoffData(dat, cutoff = 9)
#' table(cut$sim, cut$response_obs)
#' @export
CutoffData <- function(data, cutoff) {
  req <- c("sim", "accrual_time", "pfs_time", "os_time", "response", "ttr",
           "dropout_time")
  if (!is.data.frame(data) || !all(req %in% names(data))) {
    stop("'data' must be a data frame returned by rOncoEndpoints().", call. = FALSE)
  }
  sims <- sort(unique(data$sim))
  if (length(cutoff) == 1L) {
    cut <- rep(as.numeric(cutoff), nrow(data))
  } else if (length(cutoff) == length(sims)) {
    cut <- as.numeric(cutoff)[match(data$sim, sims)]
  } else {
    stop("'cutoff' must be a scalar or have one value per simulated trial.", call. = FALSE)
  }
  cut[is.na(cut)] <- Inf
  keep <- data$accrual_time < cut
  d <- data[keep, , drop = FALSE]
  cut <- cut[keep]
  # events are compared on the calendar scale so that a cutoff returned by
  # EventTime() counts the event that defines it
  cens <- pmin(d$dropout_time, cut - d$accrual_time)
  observed <- function(x) x <= d$dropout_time & d$accrual_time + x <= cut
  ev_pfs <- observed(d$pfs_time)
  ev_os <- observed(d$os_time)
  d$pfs_tte <- ifelse(ev_pfs, d$pfs_time, cens)
  d$pfs_event <- as.integer(ev_pfs)
  d$os_tte <- ifelse(ev_os, d$os_time, cens)
  d$os_event <- as.integer(ev_os)
  d$pfs_calendar_time <- d$accrual_time + d$pfs_tte
  d$os_calendar_time <- d$accrual_time + d$os_tte
  d$response_obs <- as.integer(d$response == 1 &
                                 (is.na(d$ttr) | observed(ifelse(is.na(d$ttr), 0, d$ttr))))
  d$cutoff <- cut
  rownames(d) <- NULL
  d
}
