# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generate patient-level data for one treatment group (internal)
#'
#' Internal C++ kernel of \code{\link{rOncoEndpoints}}. Random numbers are
#' drawn from the \code{dqrng} generator in the following order, each as one
#' block of \code{nsim * n} values: latent PFS score, independent normal for
#' response, uniform for the type of the PFS event, standard exponential for
#' post-progression survival, uniform for the time to response, uniform for
#' accrual, standard exponential for dropout. The draws are then transformed
#' by \code{coronco::transform_one()} (see \code{transform_core.h}).
#'
#' @param nsim Number of simulated trials.
#' @param n Number of patients per trial in this group.
#' @param lam_p,theta,c_resp,z_tau,tau Parameters of PFS and response.
#' @param os_model 0 for "idm", 1 for "expexp".
#' @param pi_death,gam0,gam1 Parameters of the illness-death model.
#' @param lam_o,c_dec,grid_g,grid_h Parameters of the exponential-exponential
#'   model and its tabulated cumulative post-progression hazard.
#' @param ttr_mode 1 to generate the time to response.
#' @param ttr_rate Rate of the untruncated time to response.
#' @param a_time,a_cum Accrual breakpoints and cumulative probabilities.
#' @param d_hazard Dropout hazard (0 for no dropout).
#' @return A list of vectors.
#' @keywords internal
generate_arm_cpp <- function(nsim, n, lam_p, theta, c_resp, z_tau, tau, os_model, pi_death, gam0, gam1, lam_o, c_dec, grid_g, grid_h, ttr_mode, ttr_rate, a_time, a_cum, d_hazard) {
    .Call(`_CorOncoEndpoints_generate_arm_cpp`, nsim, n, lam_p, theta, c_resp, z_tau, tau, os_model, pi_death, gam0, gam1, lam_o, c_dec, grid_g, grid_h, ttr_mode, ttr_rate, a_time, a_cum, d_hazard)
}

